<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>4.0.0</Version>
    <Description>A Sendy client, now supported on .Net Core!</Description>
    <Authors>Jeroen Klarenbeek</Authors>
    <Company />
    <Product />
    <RepositoryUrl>https://github.com/kloarubeek/SendyClient.Net</RepositoryUrl>
    <PackageTags>Sendy</PackageTags>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageId>SendyClient.Net</PackageId>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <FileVersion>4.0.0.0</FileVersion>
    <PackageReleaseNotes>Support for .Net 10 + latest api 7.1.1.</PackageReleaseNotes>
  </PropertyGroup>

</Project>